default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tunagu_development

test:
  <<: *default
  database: tunagu_test

production:
  <<: *default
  database: tunagu_production
  username: tunagu
  password: <%= ENV['TEAM_PROJECT_DATABASE_PASSWORD'] %>
